// GENERATED by tools/enemies.ts -- do not edit. Run `bun run tools/enemies.ts`.
//
// The three things that walk about and hurt you, two frames each.
//
// Rows of digits plus a list of colours, rather than the two-bits-a-pixel
// a CREATURE uses. A creature has to fit in a link and spec S5 fixes it at
// three inks; an enemy travels nowhere, so it can have as many materials as
// it needs -- which is what the era's best work actually had, by way of
// metasprites, and what these were missing.
//
// Cosmetic only: hard rule 4. Which one a level carries travels in the wire
// format, but no engine is ever told, and all three behave exactly as the
// single old guard did.

export interface Enemy {
  readonly name: string;
  /** What the level text calls it. */
  readonly glyph: string;
  /** Two frames: legs together, legs apart. Digits index `inks`. */
  readonly frames: readonly (readonly string[])[];
  /** Colours, indexed by digit: "1" is inks[0]. */
  readonly inks: readonly string[];
}

export const ENEMIES: readonly Enemy[] = [
  {
    name: "goblin",
    glyph: "G",
    inks: ["#61d161", "#c6e3b5", "#ffffff", "#15322a"],
    frames: [
      [
        "................",
        "..44........44..",
        ".4224......4224.",
        ".422122..221224.",
        ".42211111111224.",
        ".42211111111224.",
        ".42211311311224.",
        ".42211311311224.",
        ".42211111111224.",
        ".42214444441224.",
        ".42211111111224.",
        "..422111111224..",
        "...4221111224...",
        "....42111124....",
        "....44....44....",
        "................",
      ],
      [
        "................",
        "..44........44..",
        ".4224......4224.",
        ".422122..221224.",
        ".42211111111224.",
        ".42211111111224.",
        ".42211311311224.",
        ".42211311311224.",
        ".42211111111224.",
        ".42214444441224.",
        ".42211111111224.",
        "..422111111224..",
        "...4221111224...",
        ".4211......1124.",
        ".44..........44.",
        "................",
      ],
    ],
  },
  {
    name: "bat",
    glyph: "B",
    inks: ["#b561d1", "#4f2b82", "#ffffff", "#181532"],
    frames: [
      [
        "................",
        "......4444......",
        ".....411114.....",
        "4....411114....4",
        "24...411114...42",
        "224.44111144.422",
        "2244411111144422",
        "2224113113114222",
        "2224114114114222",
        ".22411111111422.",
        "..241111111142..",
        "...4111111114...",
        "....41111114....",
        ".....411114.....",
        "................",
        "................",
      ],
      [
        "................",
        "................",
        "......4444......",
        ".....411114.....",
        "4....411114....4",
        "24..44111144..42",
        "224.41111114.422",
        "2244113113114422",
        "2244114114114422",
        "2241111..1111422",
        "241111....111142",
        "41111......11114",
        "................",
        "................",
        "................",
        "................",
      ],
    ],
  },
  {
    name: "lizard",
    glyph: "D",
    inks: ["#61c78e", "#badecb", "#ffffff", "#193226", "#ff9f3d", "#ffe9a3"],
    frames: [
      [
        "................",
        "................",
        ".......4.4.4....",
        "......424242....",
        "...44424242444..",
        "..4211111111144.",
        ".421111111134114",
        "4211111111114441",
        "4211111111111114",
        "4211111111112224",
        ".421111111122244",
        "..4211111112244.",
        "...421..421144..",
        "...421..421.....",
        "...44...44......",
        "................",
      ],
      [
        "................",
        "................",
        ".......4.4.4....",
        "......424242....",
        "...44424242444..",
        "..4211111111144.",
        ".421111111134114",
        "4211111111114445",
        "4211111111114556",
        "4211111111112445",
        ".42111111112224.",
        "..4211111112244.",
        "...4211.4211.4..",
        "..4211..421.....",
        "..44....44......",
        "................",
      ],
    ],
  },
];

/** The enemy a level glyph means, or undefined. */
export function enemyByGlyph(glyph: string): Enemy | undefined {
  return ENEMIES.find((one) => one.glyph === glyph);
}
