// GENERATED by tools/enemies.ts -- do not edit. Run `bun run tools/enemies.ts`.
//
// The three things that walk about and hurt you, two frames each.
//
// Rows of digits plus a list of colours, rather than the two-bits-a-pixel
// a CREATURE uses. A creature has to fit in a link and spec S5 fixes it at
// three inks; an enemy travels nowhere, so it can have as many materials as
// it needs -- which is what the era's best work actually had, by way of
// metasprites, and what these were missing.
//
// Cosmetic only: hard rule 4. Which one a level carries travels in the wire
// format, but no engine is ever told, and all three behave exactly as the
// single old guard did.

export interface Enemy {
  readonly name: string;
  /** What the level text calls it. */
  readonly glyph: string;
  /** Two frames: legs together, legs apart. Digits index `inks`. */
  readonly frames: readonly (readonly string[])[];
  /** Colours, indexed by digit: "1" is inks[0]. */
  readonly inks: readonly string[];
}

export const ENEMIES: readonly Enemy[] = [
  {
    name: "goblin",
    glyph: "G",
    inks: ["#2e7a45", "#4fbb56", "#96e06b", "#cfe8b0", "#ffffff", "#15322a"],
    frames: [
      [
        "................",
        "..66........66..",
        ".6446......6446.",
        ".644344..443446.",
        ".64422233322446.",
        ".64422222222446.",
        ".64422522522446.",
        ".64422522522446.",
        ".64411111112446.",
        ".64416666663446.",
        ".64423333333446.",
        "..644222222446..",
        "...6442222446...",
        "....64111146....",
        "....66....66....",
        "................",
      ],
      [
        "................",
        "..66........66..",
        ".6446......6446.",
        ".644344..443446.",
        ".64422233322446.",
        ".64422222222446.",
        ".64422522522446.",
        ".64422522522446.",
        ".64411111112446.",
        ".64416666663446.",
        ".64423333333446.",
        "..644222222446..",
        "...6441111446...",
        ".6422......2246.",
        ".66..........66.",
        "................",
      ],
    ],
  },
  {
    name: "bat",
    glyph: "B",
    inks: ["#3d2a6b", "#8b4fc4", "#c98ae8", "#5a3596", "#ffffff", "#181532"],
    frames: [
      [
        "................",
        "6..............6",
        "64............46",
        "644..........446",
        "6444.6....6.4446",
        "6444626..6264446",
        ".64463333326446.",
        "..463552255264..",
        "...6222222116...",
        "....62255116....",
        ".....632216.....",
        ".....621116.....",
        "......6666......",
        "................",
        "................",
        "................",
      ],
      [
        "................",
        "................",
        "................",
        "................",
        ".....6....6.....",
        "....626..626....",
        "....63333326....",
        "...6355225526...",
        "..462222221164..",
        ".64462255116446.",
        "6444.632216.4446",
        "644..621116..446",
        "64....6666....46",
        "6..............6",
        "................",
        "................",
      ],
    ],
  },
  {
    name: "lizard",
    glyph: "D",
    inks: ["#2f7a5c", "#4fb882", "#8fdc9e", "#d3ecdd", "#ffffff", "#193226", "#ff9f3d", "#ffe9a3"],
    frames: [
      [
        "................",
        "........6666....",
        ".......633326...",
        ".......6325526..",
        ".....663322116..",
        "....646322446...",
        "...6446322446...",
        ".....66322446...",
        "....646322446...",
        "...6446322446...",
        ".....66322446...",
        "....626211446...",
        "..6226626.646...",
        "6226..626.646...",
        ".66..6666.6666..",
        "................",
      ],
      [
        "................",
        "........6666....",
        ".......633326...",
        ".......632552677",
        ".....66332211678",
        "....646322446.7.",
        "...6446322446...",
        ".....66322446...",
        "....646322446...",
        "...6446322446...",
        ".....66322446...",
        "....626211446...",
        "..6226626..646..",
        "6226..626..646..",
        ".66..6666..6666.",
        "................",
      ],
    ],
  },
];

/** The enemy a level glyph means, or undefined. */
export function enemyByGlyph(glyph: string): Enemy | undefined {
  return ENEMIES.find((one) => one.glyph === glyph);
}
