// GENERATED by tools/pack.ts -- do not edit. Run `bun run tools/pack.ts`.
//
// The six rooms the game opens with. Every one is checked by
// test/pack.test.ts: L1-L5, and then beaten by the bot in tools/bot.ts with
// all three ready-made creatures, with the winning run replayed to prove it.

export interface PackLevel {
  readonly slug: string;
  readonly name: string;
  /** What this room is for, in the words a child would use. */
  readonly teaches: string;
  readonly code: string;
}

export const PACK: readonly PackLevel[] = [
  {
    slug: "first-steps",
    name: "first steps",
    teaches: "pick the gems up, then the door opens",
    code: "ESGEAAOpJwekOkOkOkKGCMKA4MKA4MKSLDpDpDpDpQZYWI2RoiGk0g4",
  },
  {
    slug: "the-long-way",
    name: "the long way",
    teaches: "a room can double back — the gems are not all on your way",
    code: "ESGEAAaW-wekOkOkOkOlpBxAWkOkOkOkOlBlkYlhJaLieaCQ",
  },
  {
    slug: "four-corners",
    name: "four corners",
    teaches: "plan a loop rather than chasing the nearest gem",
    code: "ESGEAAmEzwekYKECCgoQIKChAgek4MCBAgwIECDAgFpKCAoSIICgulBolYmRDSFqbSdqJbW7lg",
  },
  {
    slug: "up-and-over",
    name: "up and over",
    teaches: "from the side: ladders go up, and gravity does the rest",
    code: "ETGEAAxyo______-f-RhRfY-RJEF4Vglut6QcQcQcQcQcQUoRQ",
  },
  {
    slug: "the-tall-room",
    name: "the tall room",
    teaches: "three floors, and the ladders are never above one another",
    code: "ETGEAA9gd______-f8MkCfAmFF8D5GkQOhMaailKZjzwhxBxBxBAhghAhxBxBxBSgDM",
  },
  {
    slug: "the-gauntlet",
    name: "the gauntlet",
    teaches: "pick the doorway that is not being walked through",
    code: "ESGEABJOSwekQQIOBhAg4GECDgWkwQIYIQIYIQIPpIECCAwQIIB6UGiUiaEPIVI9p2oqNcMd",
  },
  {
    slug: "the-hot-floor",
    name: "the hot floor",
    teaches: "the short way is on fire; the long way is not",
    code: "ESGEABU8HwekOkOkOkOkOkgMDAekOkOkOkOlBthYjhGSIqfaKMKUKcKkKsK0VkWkBA",
  },
  {
    slug: "the-narrow-way",
    name: "the narrow way",
    teaches: "a guard you can wait out, a fire you cannot",
    code: "ESGEABgp8wekYMDAwMDAwMDAmkwOCA4OCA4OCAWkgOCA4OCAmlBqlYmZDSFqbSdqJbKcW8fsJQ",
  },
  {
    slug: "mind-the-spikes",
    name: "mind the spikes",
    teaches: "walk through for a heart, or go round the long way",
    code: "ETGEABsXx______-f-RhRfY-R5EF6Vel0pQlpFrN6QcQcQcQcQcQUoBV",
  },
];
