// GENERATED by tools/pack.ts -- do not edit. Run `bun run tools/pack.ts`.
//
// The six rooms the game opens with. Every one is checked by
// test/pack.test.ts: L1-L5, and then beaten by the bot in tools/bot.ts with
// all three ready-made creatures, with the winning run replayed to prove it.

export interface PackLevel {
  readonly slug: string;
  readonly name: string;
  /** What this room is for, in the words a child would use. */
  readonly teaches: string;
  readonly code: string;
}

export const PACK: readonly PackLevel[] = [
  {
    slug: "first-steps",
    name: "first steps",
    teaches: "pick the gems up, then the door opens",
    code: "ESKAAAOpJwekOkOkJAwSLg4aIOGiDg-kOkMiBAw6Q6UGqFiNkaIiIqJ-stx6wyebOLE",
  },
  {
    slug: "the-long-way",
    name: "the long way",
    teaches: "a room can double back — the gems are not all on your way",
    code: "ESKAAAaW-wekOkOkOkIh4gOkHEBaQ6Q6Q6Q6UGeRiWElouJ5o98jPLg",
  },
  {
    slug: "four-corners",
    name: "four corners",
    teaches: "plan a loop rather than chasing the nearest gem",
    code: "ESKAAAmEzyeEYKECCgoQIKChAgek4MCBAgwIECDBA6SggKEiCAoLpQapWJkQ0ham0naiXVuwzzV8KA",
  },
  {
    slug: "up-and-over",
    name: "up and over",
    teaches: "from the side: ladders go up, and gravity does the rest",
    code: "ETKAAAxyo______-dcQGDOHDkiEl5HkQXpWiXKhqWfLj_6QcQcQcQcQcQcjM",
  },
  {
    slug: "the-tall-room",
    name: "the tall room",
    teaches: "three floors, and the ladders are never above one another",
    code: "ETKAAA9gd______-d4IUUkCVAgZhRfA-SJEDoTGmopSmZjJzT_PCHEHEHEECGCECHEHEHEFKng",
  },
  {
    slug: "the-gauntlet",
    name: "the gauntlet",
    teaches: "pick the doorway that is not being walked through",
    code: "ESKAABJOSwekQQIOBhAg4GECDgQBQg7BAhghAhghAg-kgQIIDBAggHpQapSJoQ8hUj2naipVwz1yG8C-",
  },
  {
    slug: "the-hot-floor",
    name: "the hot floor",
    teaches: "the short way is on fire; the long way is not",
    code: "ESKAABU8HwYBZDpDpDpDpDpIDAwHIhQjpDpDpDpQb4WI4RkiKn2ijClCnCpCrCtFZFpA17L4GQ",
  },
  {
    slug: "the-narrow-way",
    name: "the narrow way",
    teaches: "a guard you can wait out, a fire you cannot",
    code: "ESKAABgp8yeEYMDAwMDAwMDAmkwOCA4OCA4OCAVEAoDggODggJpQbJWJmQ0ham0naiXSnFvH7Az7s4Bq",
  },
  {
    slug: "mind-the-spikes",
    name: "mind the spikes",
    teaches: "walk through for a heart, or go round the long way",
    code: "ETKAABsXx______-e6QEGCYMJgn2PkqRBfFXpcJeqUKWSWxXcsv3pBxBxBxBxBxBSsI",
  },
  {
    slug: "the-reef",
    name: "the reef",
    teaches: "strength beats a current, speed goes round the long way",
    code: "EUGAAFIDM______-fkGkOkOkOkIh4gMES6Q6Q6Q6Q6Q6UGoNCOkZouKYqTSTyWw9-jOKuZozpoDRmEU",
  },
  {
    slug: "the-tall-rocks",
    name: "the tall rocks",
    teaches: "weave between the stacks; a current across pushes you off",
    code: "EUGAAE7QEAAAAQAAAwAAAwAAAwAEAwgEAwgEQwiEQwiGQwyEQwiEQwiEQwiEQ____rDQIpEaaCb6jqlUlcmEZ_N7zDZG6OErhYCyAFA",
  },
  {
    slug: "the-wreck",
    name: "the wreck",
    teaches: "down into the hold, and strength is what gets you back out",
    code: "EUGAAF1J0______-fkGkOkOkOkOCDiwIDiQCQuQkGiBCQaIEJBogRYQ6UGoNAilAqCqFKLqTyURMdCfGz9z7_5Y",
  },
  {
    slug: "the-garden",
    name: "the garden",
    teaches: "pick the flowers, mind the bear, keep out of the ponds",
    code: "EVFAACMl8wekPCJAAyQEMiFCOkMEAgAsGiOkNCEiIHImQgYBwjpQdhkJqSGiyjolkoqoyo0jnk7Wi5HZNkpErEtGJGLGNCD6w7Wkn2SX",
  },
  {
    slug: "the-beach",
    name: "the beach",
    teaches: "pick the shells up, mind the crab, keep out of the sea",
    code: "EVFUACA4HwekMCFiPCgiKOBAIiBA4iAiIEDiAiIiA8I6Q2QAMiFCOkOlB2DQFxRSSqcieagCh6jiHNN1gbi-icislMlUlclsl0RPPv9-YcQcQUgs",
  },
  {
    slug: "the-city",
    name: "the city",
    teaches: "get the people to the evac zone, and mind the kaiju",
    code: "EWDYACOpWf___wAAA3re43re63re4xAAI3vW43vW43vW4wAAA1ve61ve4wAAA____wDImpDiEyFaPaRilKKDWteeQcb0dEPnIvxC",
  },
  {
    slug: "the-jungle",
    name: "the jungle",
    teaches: "cross the creek on the log, pick the fruit, mind the jaguar",
    code: "EVFcADdrCwekIFJCBCDig6QyQEOkOkOkKDIkIwRCLhgjpQdoUCKSCiGj2kknuowkrVzmRoCynCpDXDZE3E5FnFpCz7f7MEcyYCE",
  },
  {
    slug: "the-pyramid",
    name: "the pyramid",
    teaches: "four chambers, four amulets, and traps in the doorways",
    code: "ESKgAFSHjf___wkAkwkQk0AAA9_v79_v7wBJIxBJIwAAA_v99_v990AAAwAAA____uVQFxGSIykSmyGzITWdXONkc8JXQrzZ",
  },
  {
    slug: "the-station",
    name: "the station",
    teaches: "three decks, two ladders, and vents on the floor",
    code: "ETKkAFINV______-d4IMFDJAnwJhRfA-TJEDoTGjamopSmY5npPJfDJxs_PCHEHEHEECGCECHEHEHEFKLQ",
  },
];
