// Inlines levels/*.lvl into a TS module so the web build needs no fetch.
// The .lvl file is canonical; this output is generated. `bun test` fails if
// the two drift, so regenerate with `bun run tools/embed-levels.ts` after editing.

const HEADER = `// GENERATED by tools/embed-levels.ts -- do not edit by hand.
// Canonical source: levels/*.lvl

`;

// name in the generated module -> file on disk. Append only; the day 1 level
// stays because the day 1 golden vector pins it.
export const EMBEDDED: ReadonlyArray<readonly [string, string]> = [
  ["DAY1_LEVEL_TEXT", "levels/day1.lvl"],
  ["DAY2_LEVEL_TEXT", "levels/day2.lvl"],
  ["DAY3_LEVEL_TEXT", "levels/day3.lvl"],
  ["DAY4_LEVEL_TEXT", "levels/day4.lvl"],
  ["DAY7_LEVEL_TEXT", "levels/day7.lvl"],
  ["ROAM1_LEVEL_TEXT", "levels/roam1.lvl"],
  ["DASH1_LEVEL_TEXT", "levels/dash1.lvl"],
];

export async function renderEmbedModule(): Promise<string> {
  let out = HEADER;
  for (const [name, path] of EMBEDDED) {
    const literal = JSON.stringify(await Bun.file(path).text());
    out += `export const ${name} = ${literal};\n`;
  }
  return out;
}

if (import.meta.main) {
  const out = await renderEmbedModule();
  await Bun.write("src/core/fixtures.ts", out);
  console.log(`wrote src/core/fixtures.ts (${EMBEDDED.length} levels)`);
}
