// Inlines levels/*.lvl into a TS module so the web build needs no fetch.
// The .lvl file is canonical; this output is generated. `bun test` fails if
// the two drift, so regenerate with `bun run tools/embed-levels.ts` after editing.

const HEADER = `// GENERATED by tools/embed-levels.ts -- do not edit by hand.
// Canonical source: levels/*.lvl

`;

export async function renderEmbedModule(): Promise<string> {
  const text = await Bun.file("levels/day1.lvl").text();
  const literal = JSON.stringify(text);
  return `${HEADER}export const DAY1_LEVEL_TEXT = ${literal};\n`;
}

if (import.meta.main) {
  const out = await renderEmbedModule();
  await Bun.write("src/core/fixtures.ts", out);
  console.log("wrote src/core/fixtures.ts");
}
